<?php
declare(strict_types = 1);

use Magento\Framework\View\Element\Template;
use Tweakwise\TweakwiseJs\Model\Enum\SearchType;
use Tweakwise\TweakwiseJs\ViewModel\Search;

/** @var Template $block */

/** @var Search $viewModel */
$viewModel = $block->getViewModel();
?>

<?php if ($viewModel->getSearchType() === SearchType::SUGGESTIONS->value): ?>
    <script>
        const input = window['twn-starter-config'].input;
        window['twn-starter-config'].input = null;
        window.addEventListener('DOMContentLoaded', function () {
            window.tweakwiseSuggestions({
                input: input,
                instancekey: "<?= $viewModel->getInstanceKey();?>",
                cid: "<?= $viewModel->getStoreRootCategory();?>",
                searchPhrases: {
                    handle: ({ data }) => {
                        location.href = '<?= $viewModel->getSearchUrl();?>?tn_q=' + data.match;
                    }
                }
            });
        });
    </script>
<?php elseif ($viewModel->getSearchType() === SearchType::INSTANT_SEARCH->value): ?>
    <script>
        // TODO: PREVENT SEARCH FORM FROM SUBMIT
        // window.addEventListener('DOMContentLoaded', function () {
        //     var form = document.getElementById('search');
        //     form.onkeydown = function(event){
        //         event.preventDefault();
        //     };
        // });
    </script>
<?php else: ?>
    <script>
        window['twn-starter-config'].input = null;
    </script>
<?php endif; ?>
